### ISSUE TITLE
Custom content-type support 

### ISSUE THREAD

**Issue by hellboy81** [mscdex/busboy#101]
How can I handle `application/json` and `application/xml` content types?

**Comment by mscdex** [comment]
You have to handle those yourself. Busboy's focus is on `multipart/form-data` and `application/x-www-form-urlencoded` forms.

**Comment by Marak** [comment]
@hellboy81 - Hello, good to see you :-)

You *might* find this module useful. It's general module for parsing incoming streaming requests.

It doesn't have xml support yet, but I'd be happy if you added it.



https://github.com/bigcompany/parse-service-request/blob/master/index.js

**Comment by DylanPiercey** [comment]
@mscdex Is there any chance that busboy will support application/json and/or application/xml in the future?

**Comment by mscdex** [comment]
@DylanPiercey Probably not. There are streaming parsers for JSON and XML on npm though if you need that that kind of parsing ability.

**Comment by Marak** [comment]
@DylanPiercey -

I've got a library / middleware we are using in production at hook.io for handling all incoming streaming requests ( it's based on busboy ). It will do json and multipart ( among other things )

I keep spamming the library here on @mscdex `busboy` project because I feel it's a common problem that people are having and with a little work we can have a nicely tested and documented module.

Check out https://github.com/bigcompany/parse-service-request

This module is in heavy production usage.
