### ISSUE TITLE
Allow only one attachment in multipart upload

### ISSUE THREAD

**Issue by hellboy81** [mscdex/busboy#102]
How can I allow/handle only one (first) attachment?

I.e. event `busboy.on('file', ...` should be raised only once.

**Comment by Marak** [comment]
The way I understand it, that event will be raised every time a file field is found.

It might be possible that `busboy.once` is available, but I haven't tested it.

If anything, you could just create a counter and only process the event the first time it's raised.

A better question might be, why do you need to ignore file fields? Wouldn't you just want to remove the field from the submitted form in the first place?

**Comment by mscdex** [comment]
It depends on what is an acceptable solution, you could do one of:

* As Marak said, only send one from the client if you are in control of that.
* Simply throw away any additional file streams (this is necessary if you want to continue parsing) via `file.resume()`.
* Immediately send an appropriate HTTP response when you detect more than one file.

Using `.once()` (while it is supported since it is an EventEmitter) won't typically work since the parser will stop if the current file stream's internal buffer fills up. This is to avoid buffering a lot of data in memory and keeps with the spirit of streaming.

**Comment by hellboy81** [comment]
IMHO I should never use Multipart uploads if I *only one* file should be uploaded.

As I mentinoed It was my engineering pitfall. At the begining I don't know in C#/RestSharp ()client side and Node.js (server side) how to implement request piping.

I have choosen `formidable` and `AddFile` from`RestRequest::RestSharp`

**Comment by mscdex** [comment]
Just so you know, `formidable` is a multipart parser also so you're not exactly getting away from multipart in that case. If you're saving to disk (which would be the case with `formidable`), there is also `multer` which basically does the same thing, but is built on top of `busboy` for better performance.
