### ISSUE TITLE
Caching files in memory 

### ISSUE THREAD

**Issue by m4nuC** [mscdex/busboy#109]
I'd need to buffer file streams, in memory, while waiting for the `finish` event. From there i'd pass them to the S3 upload stream. Is there a straight forward way to do so ?

Thanks

**Comment by mscdex** [comment]
Why do you *need* to buffer the files if you're going to pass them to S3?

**Comment by m4nuC** [comment]
I need to run validations on the inputs before uploading to S3 so I am trying to avoid saving them to disk and just buffer then in memory instead. 
On 29 Dec 2015 21:25, Brian White <notifications@github.com> wrote:Why do you need to buffer the files if you're going to pass them to S3?

**Comment by mscdex** [comment]
Are you referring to inputs other than the files you're uploading (e.g. text fields)? If so, you can just move those fields before the file fields before submitting the form. If you want to preserve the current order, you can either:

 * Submit a reordered form via XHR
 * Use hidden fields (placed before the file fields) that store a copy of the actual, visible (text/checkbox/etc.) fields that get updated when the real fields change
 * (Hide and) reorder the actual field elements in the DOM right before form submission

Using one of these methods will allow you to receive the fields before the files, allowing you to avoid buffering entire files in memory (which is generally a bad idea).

**Comment by minecrawler** [comment]
as @mscdex wrote, caching in memory is bad, because: files might be very big or lots of users might upload small files simultaneously which floods your memory. Also `Never trust your users`. They might forge requests with many large files in order to DoS your server.
I think the best way would be to do your checks on the fly inside the `data` event and then pass the chunks to your upload pipeline. You could stream the files from the client to S3 that way. But that depends heavily on the kind of checks you want to do. In case you cannot do the checks on the fly, the probably most-used way is to cache them to a tmp directory on the server, do your checks on the file system and then upload the files. This also enables you to delay all checks, accumulate them and finally do them when server load is low, schedule a task or even push them to a different server to do your checks there.
Always try to prioritize serving users over doing background jobs like uploading files to the cloud. 

Additionally to @mscdex three ideas I want to mention `CSS`. The easiest non-script way to visually rearrange your form without ever touching the DOM. That should be the first or second idea that comes to mind imho.

**Comment by m4nuC** [comment]
@mscdex OK thanks for answer. I did arrange files so that they are sent last. But still has issues due to the implantation I was using. ( Basically [co-busboy](https://www.npmjs.com/package/co-busboy) where I replaced the Chan module for [async-csp](https://github.com/dvlsg/async-csp) ). I ended up writing a small wrapper around busboy to get a half promise half CSP based interface that solved my issues.

@minecrawler Yeah that makes sense. Thanks for the input.
