### ISSUE TITLE
busboy doesn't call it's "next" callback?

### ISSUE THREAD

**Issue by sherifnada** [mscdex/busboy#118]
Hi, 

I opened [this issue](https://github.com/expressjs/multer/issues/325) in [Multer](https://github.com/expressjs/multer/) and the repo maintainer suggested it might be a problem with busboy? Reporting it here for your consideration. 

Thanks.

**Comment by mscdex** [comment]
`busboy` doesn't have a "next" callback, that's purely an Express/`multer` thing.

The problem with the raw form data you've posted in expressjs/multer#325 is that it's not formatted properly. The boundaries in the actual body of the request need to have an extra `--` prepended to the boundary value found in the `Content-Type` header in order to be compliant with the multipart specification.

Additionally you need to ensure there is a `filename` parameter if you want the field to be detected as a file, otherwise the content will be treated as a non-file field.
