### ISSUE TITLE
Pipe file stream directly to another server without storing it on disk or memory.

### ISSUE THREAD

**Issue by ADjenkov** [mscdex/busboy#132]
Hi guys,
I'm trying to redirect the incoming file (single file (no other fields required) incoming from multipart/form-data throughout some html client) directly to another server (endpoint that also handles multipart/form-data). I've checked other closed issue https://github.com/mscdex/busboy/issues/109 in which @minecrawler was talking about something closer to my problem. I don't want to do any additional checks over the file. Just to redirect the upload of the file without filling up my server memory or disk.

Using:
nodejs application with `express` and `request`

Currently I'm doing this in my `/upload` endpoint: 

```js
        req.busboy.on('file', function (fieldName, fileStream, fileName) {

            var options = prepareUploadOptions(req.headers['content-length'], fileStream, fileName, context.account.masterKey);

            request.post(options, function onFileUploaded(err, response, body) {
                ....
                }
```

Where `prepareUploadOptions` is something that prepares the upload request to the remote server:

```js
function prepareUploadOptions(contentLenght, fileStream, fileName, masterKey) {

    var options = {
        url: 'https://sit-tap-bs.telerik.rocks/v1/apikey/Files',
        formData: {
            file: {
                value: fileStream,
                options: {
                    filename: fileName,
                    contentType: 'application/octet-stream',
                    knownLength: contentLenght
                }
            }
        },
        headers: {
            'Transfer-Encoding': 'chunked',
            Authorization: 'Masterkey ' + masterKey
        }
    };

    return options;
}
```

I think the approach works. I'm uploading the file successfully to the remote server (with its original size/extension etc), but I think that the upload to the remote server doesn't  start until the entire file is Buffered to my server (which actually fills up my server memory and the approach breaks for larger files). 

Am I doing it wrong/right? Is this even possible? Any other info I should provide?

**Comment by mscdex** [comment]
Using `req.headers['content-length`]` isn't correct, not only because the server may not specify it up front, but also because that value would refer to the entire response body and not that specific file. Even if there is just one file in the incoming request, there is still a lot of other information in the request besides the raw data, such as multipart boundaries, headers, etc.

`request()` uses `form-data` which only allows certain kinds of streams, specifically those that it can determine the total length of up front since it *always* adds a Content-Length header in the request (although node supports sending chunked requests).

You would probably need to submit a PR to `form-data` to allow any streams, and to use chunked encoding if any of the streams' lengths cannot be pre-determined.

**Comment by minecrawler** [comment]
Do not rely on headers, as they can be forged. Instead, pipe the stream until it ends or you hit a quota or limit. I'd go as far as writing my own stream which checks for a certain max. length and stops the transfer in case the length limit is reached. Just pipe from stream to stream to post-transfer!

As for your problem: Have you already tried to use multipart (instead of formData) with the `chunked` option set to true? You can easily test your setup by downloading a file generator and creating a big file (maybe 1GB). Then you start the upload and see if the transfer starts right away. You can also test your limiters that way :)

**Comment by ADjenkov** [comment]
Thanks a lot for the help guys!! I've tried with 'multipart' instead of 'formData' , but It turned out that the targeted server doesn't support 'multipart/related' requests (which is the case with `multipart` request).

Thanks again, I'm closing the issue

**Comment by athiselvam** [comment]
@ADjenkov  Did you solve this problem? I'm also facing the same issue. If you can help me I'm thankful to you.
