### ISSUE TITLE
Ideas about max files per field option?

### ISSUE THREAD

**Issue by tunnckoCore** [mscdex/busboy#153]
I see that there is `opts.limits.files` option, but it sounds like it is for how much **file _fields_** is allow, not how much files are allowed per field? Because we can have single file field, but can upload multiple files from it, so i want to be able to limit that case. Is it possible to detect that situation and probably expose an option for it?

**Comment by mscdex** [comment]
Presumably you'd need to manually check/parse the field names to handle that kind of thing. That's a bit out of scope for this module, especially since clients may send "duplicate" fields in many different ways (e.g. 'foo,foo,foo' or 'foo[],foo[],foo[]', or 'foo[0],foo[1],foo[2]' or 'foo_1,foo_2,foo_3').
