### ISSUE TITLE
Busboy sometimes often throws Unhandled 'error' event Unexpected end of multipart data

### ISSUE THREAD

**Issue by david1921** [mscdex/busboy#171]
Hi everyone

I am using node v6.10.3 and Busboy 0.2.14.
I use busboy  to  stream jpg image to a node server. But the issue is sometimes it works and some times it fails with the folowing error and crashes my server.

`events.js:183
066466+00:00 app[web.1]: throw er; // Unhandled 'error' event
2018-06-19T00:45:07.066468+00:00 app[web.1]: ^
2018-06-19T00:45:07.066470+00:00 app[web.1]: 
066472+00:00 app[web.1]: Error: Unexpected end of multipart data
2018-06-19T00:45:07.066474+00:00 app[web.1]: at 
/app/node_modules/busboy/node_modules/dicer/lib/Dicer.js:62:28`

Here is my code to handle the file

     req.busboy.on('file', function (fieldname, file, filename) {
       console.log("Uploading: " + (filename)); 
       fstream = fs.createWriteStream(__dirname + '/public/img/'+ filename);

       file.on('data', function(chunk) {
         fstream.write(chunk);
       });

       file.on('end', function() {
         fstream.end();
         console.log('File [' + fieldname + '] Finished sucessfully');
        });
      file.on('error',function(err){
        console.log('fstream error' + err);
        file.unpipe();
      });
    });

I have tried to follow similar issues online, but no success.
Can somebody please help me what could be the issue here? Thank you in advance.

**Comment by mscdex** [comment]
A few immediate related/unrelated things:

* Did you add an error handler on `req.busboy`?

* Using `filename` (which comes directly from the http client) as-is, especially when concatenating with a path, is a very bad idea because someone could use a malicious value to write to some place outside of the directory you intended using a relative path as the filename. If you absolutely need to maintain the original filename (and it's not empty), you should use node's built-in `path` module to resolve the result of concatenating your base path with `filename` and then ensuring the resulting path still starts with your base path.

* `file.unpipe()` as used in your current snippet is of no use since you're not piping anywhere to begin with.

The reason for the error though is that the form being submitted is incomplete (probably missing the final 'end of parts' identifier). How is the form being submitted? Are you able to capture a raw copy of the problematic form data that's being passed to busboy so we can verify the form is in fact incomplete?

**Comment by david1921** [comment]
@mscdex  Thank you for the input. 

- you mean error handler something like ` req.busboy.on('error',`
If that what you mean then No.

- The image is coming from camera module/microcontroller. The form is built on there and submit it as image binary data to the server. And I would say 70% of the time it works fine. How is that possible?

**Comment by mscdex** [comment]
> Do you mean error handler something like req.busboy.on('error',

Yes.

> The image is coming from camera module/microcontroller. The form is built on there and submit it as image binary data to the server. And I would say 70% of the time it works fine. How is that possible?

It's hard to say, it could be a buggy client. I would suggest trying to capture the raw form data when the error occurs, so we can verify this is the case.

**Comment by david1921** [comment]
It works now. I was not handling the error correctly. Thank you so much @mscdex

**Comment by trunderman** [comment]
@david1921 how did you go about handling the error correctly?

**Comment by 0xCAFEADD1C7** [comment]
@trunderman If you still need the answer, you must add an error handler to the file objected got from busboy. 
You'll have something like : 
```js
busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
  // with this handler, it won't throw at a higher level
  file.on('error', function(err) {
    // do whatever you want with your error
  })
});
```

**Comment by coderbuzz** [comment]
@mscdex @0xCAFEADD1C7  what should we do ideally on file error handler? Ignore it or close the file stream?
If we close the file or ignore it does we still get parser.on('close') event? (because parser close is important to resolve the result)

Here my code:

``` javascript
...
  const parser = busboy({ headers: request.headers });
  const formData = new FormData();

return new Promise((resolve) => {

  parser.on('field', (name, value) => {
    formData.append(name, value);
  });

  parser.on('file', (name, file, info) => {

    const entry = {
      name,
      type: info.mimeType,
    }

    formData.append(name, entry);

    info.ext = path.extname(info.filename);
    info.basename = path.basename(info.filename);

    const saveAs = options.saveAs ? options.saveAs(info) || generateUUID() : info.filename;

    file.on('error', (err) => {
      // what should we do here
    })

    if (!options.saveTo || !saveAs) {
      // eat stream
      file.on('data', () => { });

    } else {
      entry.filename = path.join(options.saveTo, saveAs);
      entry.ext = path.extname(entry.filename);
      entry.basename = path.basename(entry.filename);

      file.pipe(fs.createWriteStream(entry.filename));
    }

  });

  parser.on('close', () => {
    resolve(formData);
  });

  request.pipe(parser);

})
```

**Comment by mscdex** [comment]
@coderbuzz The only time a file stream can emit an error is when it's being destroyed because there was a form parsing error. In that case, the parser halts immediately and destroys itself as well. As far as what gets emitted when a stream is destroyed, that is up to node.

As far as I'm aware, `'close'` should be emitted whether there was an error or not.

**Comment by coderbuzz** [comment]
Ok, after giving error handle `file.on('error'` the app still crashes when an error occurs.

What is the proper error handle to prevent app crashes? `parser.on('error'`?

**Comment by mscdex** [comment]
You should also have an error handler for the busboy instance itself.

**Comment by coderbuzz** [comment]
@mscdex  OK, so `parser.on('error'` in this case right?

**Comment by mscdex** [comment]
Yes.

**Comment by coderbuzz** [comment]
OK thanks!
