### ISSUE TITLE
[Feature Request] Send `files` and `fields` as parameters in `finish` event

### ISSUE THREAD

**Issue by BrodaNoel** [mscdex/busboy#193]
Guys,
What about sending `files` and `fields` as parameters in the `finish` callback?

```js
busboy.on('finish', (files, fields) => {
  //
});
```

**Comment by mike-marcacci** [comment]
Hi @BrodaNoel, what exactly would you want the files parameter to contain? The incoming data must be read in order, so if you were to pass the file streams in that parameter, they would all be finished, which sounds pretty useless to me.

**Comment by BrodaNoel** [comment]
@mike-marcacci thank you for your quick answer!

Honestly, I'm not sure how this library is coded, but let me write some pseudo-code about what I'd do in my proposal:

```js
// You read the files
foo.readFiles().forEach((file) => {
  // Call the `file` event sending the `fieldname, file, filename, encoding, mimetype` parameters
  busboy.emit('file', [fieldname, file, filename, encoding, mimetype]);
});

// Then you emit the `fields` events
fields.forEach(({ fieldname, value }) => {
  busboy.emit('field', [fieldname, value]);
});

// Finally, you call the `finish` event, with no parameters
busboy.emit('finish');
```

Now, what if you temporally save the `files` and `fields`, and then you send them through the `finish` event? Something like this:

```js
// You read the files
let files = [];
foo.readFiles().forEach((file) => {
  // Call the `file` event sending the `fieldname, file, filename, encoding, mimetype` parameters
  busboy.emit('file', [fieldname, file, filename, encoding, mimetype]);
  
  // save the file to send them in `finish` event
  files.push([fieldname, file, filename, encoding, mimetype]);
});

// Then you emit the `fields` events
let fields = [];
fields.forEach(({ fieldname, value }) => {
  busboy.emit('field', [fieldname, value]);

  // save the field to send them in `finish` event
  fields.push([fieldname, value]);
});

// Finally, you call the `finish` event, send `files` and `fields` as parameters
busboy.emit('finish', [files, fields]);
```


So then, we'll be able to use it in this way:
```js
busboy.on('finish', (files, fields) => {
  //
});
```

I understand that things are not THAT easy, always, but it's just an idea/approach.

Maybe sending files is not that easy, due to they are streams, but at least you can send the fields+values.

**Comment by mike-marcacci** [comment]
Hi @BrodaNoel,

I think what you're proposing is beyond the scope of busboy. An incoming multipart request is going to be a single stream, with parts in a given sequence, let's say we have have a request structured like `aABCbD` where capital letters represent files, and lowercase letters represent form data. The problem is that we have to read all the contents of `A` before we can even start reading `B`. Busboy makes a rather sane assumption here that form data (lowercase letters) will be small enough to parse and store in memory while files (uppercase letters) may not. This is why it emits a stream in each `file` event, which maps directly to the subset of the original request containing that file; if you never consume (or discard, which is reading into nothing) file `A`, you will never get an event for files `B`/`C`/`D`, or form data `b`; at the same time, if you discard the data from `A` to get to `B`, you don't have it anymore, and the complete stream is useless when the `finish` event happens.

The problem is that the data for file `A` has to go *somewhere*. If you want to wait for everything to upload and *then* process the request (which does make things nice and tidy, at the expense of performance), you might try writing the data to the filesystem (probably in `os.tmpdir()`). If you have a highly variable execution path (like a GraphQL server) and want to squeeze out as much performance as possible, you can use something like [fs-capacitor](https://github.com/mike-marcacci/fs-capacitor) to buffer these streams to the filesystem. However, in an ideal scenario, you would just handle the file streams directly, as soon as they're emitted from busboy.

Hope that makes sense!

**Comment by BrodaNoel** [comment]
Makes all the sense!
Thank you a lot for your time!
