### ISSUE TITLE
increasing file chunk size

### ISSUE THREAD

**Issue by yektayazdani** [mscdex/busboy#196]
Thanks for the great library.

I need to stream csv files which sometimes are huge. for instance I have a csv file which consists of 1000 columns. 

inside the `file.on('data', ()=>{})` event upon receiving the chunks, I get only two rows due to the number of columns and this causes computation overhead.

Is there a way you can set the chunk size for each file coming through the `file.on('data', ()=>{})`

I have already tried setting the `highWaterMark` and  `fileHwm` config while initializing busboy. 
`let busboy = new Busboy({ headers: req.headers, highWaterMark: 1024000, fileHwm:1024000});`
but there was no luck.

Thanks in advance for your help.

**Comment by mscdex** [comment]
This is more of a general node streams thing, but instead of using `'data'` events, you could utilize `file.read(n)` and the `'readable'` event instead if you want to read a specific number of bytes (where possible). Otherwise no, there is no way to increase the chunk size because either way the memory is getting buffered somewhere, whether it'd happen within node core or by the end user.

**Comment by arekbal** [comment]
@yektayazdani How about you buffer these chunks together until you got big enough batch(like 50 rows) to start processing?
