### ISSUE TITLE
how can I report a security issue?

### ISSUE THREAD

**Issue by Jinmo** [mscdex/busboy#198]
Could you tell me where to report security issues? Thank you.

**Comment by mscdex** [comment]
You can send them to security_(at)_mscdex dot net.

**Comment by marksteward** [comment]
Hi, I'm just working back through some overdue vulnerability disclosures, and it looks like this issue was fixed but no advisory issued. We found what I believe is the same issue independently in 2018.

It's important to make users aware when versions of a library have security issues, so that they know to upgrade even if they weren't planning to. This is now really easy with Github's advisory functionality. I'd also suggest getting a CVE in this case.

If you did make this clear somewhere, but I can't see it, please accept my apologies of course!
