### ISSUE TITLE
Is it possible to intercept a multipart file upload and pipe it to another api?

### ISSUE THREAD

**Issue by u84six** [mscdex/busboy#224]
I'm in dilemma where I have an express based rest api and need to upload mulitpart files (basically, large files that exceed 1GB) and send them through to another 3rd party api. My first approach was to upload the file and write it to disk, and when the file upload completes, read it in with a read steam and send it to the 3rd party api. While this work, it could be a problem with performance, disk space, etc. What I would really like to do is pass the request to the 3rd party api so that the stream passes between my api and the 3rd party api. I can't change the 3rd party api and it works like this:

api.files.getUploader(location_id, fileSize, filename, readStream)
.then(uploader => {
    uploader.start()
})
.then(fileInfo => {
    console.log('upload complete'
})

Is there a way I can pipe the file upload stream into the read steam that this api is expecting? I'll also need the file size as you can see from the example.

**Comment by mscdex** [comment]
If it *requires* the file size up front, then you're generally going to be out of luck because of the nature of `multipart/form-data` (where parts are separated by string boundaries and are not length-prefixed). This means you're have to save the entirety of the file *somewhere* first to be able to obtain the file size.

However, you could send the file size (available in the browser when using the `FormData` web API for example) as a separate (hidden) text field that comes before the file field in the form and use that.

**Comment by u84six** [comment]
> If it _requires_ the file size up front, then you're generally going to be out of luck because of the nature of `multipart/form-data` (where parts are separated by string boundaries and are not length-prefixed). This means you're have to save the entirety of the file _somewhere_ first to be able to obtain the file size.
> 
> However, you could send the file size (available in the browser when using the `FormData` web API for example) as a separate (hidden) text field that comes before the file field in the form and use that.

Yeah, I suppose I could use the hidden field. Thanks for the tip!
