### ISSUE TITLE
Any issues with Node14?

### ISSUE THREAD

**Issue by amit777** [mscdex/busboy#235]
I'm currently using a module called async-busboy which is a wrapper around this lib.  https://github.com/m4nuC/async-busboy#readme

I've noticed that when we update to Node 14, async-busboy stops working.  It looks like others are reporting the same issue.  Is there anything obvious about Node 14 that would affect this module?  I've looked through the code for async-busboy and it looks pretty simple so I'm not sure why a node14 upgrade would break it.

Someone else opened a github issue on the other repo:  https://github.com/m4nuC/async-busboy/issues/42

Thanks for your time and apologies for cross posting this issue.  Just trying to narrow down why it may be happening.

**Comment by mscdex** [comment]
I don't know of anything offhand.

**Comment by amit777** [comment]
So I've traced the code a bit, and it seems when the following code is called, our lib seems to hang:

inside Busboy.prototype.emit
```js
 if (ev === 'finish') {
    if (!this._done) {
      this._parser && this._parser.end();
      return;
    }
```

I also notice that in my debugging that a "prefinish" event is fired when things hang.  It feels like some sort of race condition.

**Comment by amit777** [comment]
I think I figured out part of the problem.  The async-busboy package seems to rely on the "finished" event being called before the "close" event.  I'm wondering if Node14 has any changes in assumptions on the ordering of events.

**Comment by mscdex** [comment]
It could very well be that node changed the order of events.

**Comment by amit777** [comment]
closing this issue as it seems like a problem withe event order expecations of async-busboy package.

**Comment by paxcol** [comment]
Even if the issue is closed, I think it is still interesting to leave a comment here, in the [documentation of node js](https://nodejs.org/api/stream.html#stream_event_close), it says that:
> The 'close' event is emitted when the stream and any of its underlying resources (a file descriptor, for example) have been closed. The event indicates that no more events will be emitted, and no further computation will occur.

I tested that the version 14.x of nodejs still emits the `finish` and `close` events in the correct order(`finish` before `close`). However, what breaks for `async-busboy` is [here in the codebase of busboy](https://github.com/mscdex/busboy/blob/5ef3f9b1d08e7ccb7c9b3690e4c071089e66285c/lib/main.js#L28) where all the `finish` events are emitted in the `nextTick`. This bug of async-busboy only surfaced in node 14.x, perhaps because of some change(need to confirm).

The question is since Busboy is a WritableStream and also a userland library, should it always stick to the documentation of nodejs?
