### ISSUE TITLE
Resumable file upload using busboy

### ISSUE THREAD

**Issue by soubhikchatterjee** [mscdex/busboy#239]
I am implementing an upload endpoint using express and busboy. The code works like a charm. I am trying to implement the logic of resumable uploads. For eg, if a user is uploading a 10gb or 50gb file, and if their internet disconnects, and next time when they are uploading the same file, it should resume.

I do understand that I need to implement another endpoint that should tell the client how many bytes has been uploaded so far, so that the client can send the remaining bytes.

I am not sure how to proceed from here, because the first problem i am facing here is that when the upload happens, express uploads the temp file in the tmp directory of the OS. Is it possible to upload the temp file in my current script directory?

Following is my upload endpoint code. 

    router.post("/upload", (req, res, next) => {
      const busboy = new Busboy({ headers: req.headers });
      req.pipe(busboy);
      busboy.on("file", (fieldname, file, filename) => {
        const filepath = path.join(__dirname, filename);
        var writeStream = fs.createWriteStream(filepath);
    
        file.pipe(writeStream);
        writeStream.on("close", () => {
          res.send(filename);
        });
      });
    });

**Comment by mscdex** [comment]
You should never use `filename` directly like that as it can be a source of security issues. Either generate a unique name or [hash the `filename`](https://nodejs.org/docs/latest/api/crypto.html#crypto_crypto_createhash_algorithm_options) first using whichever algorithm you like. The reason for this is that malicious clients can provide a relative path (e.g. `'../../../../../etc/resolv.conf'`) for the `filename` to try and overwrite critical/system files for example.

As far as Express goes, it sounds like you're already using some other module that is handling multipart form requests, otherwise you wouldn't have uploads automatically landing in the OS's temporary directory. So you'd either need to remove that module and handle everything yourself or make the `use()`ing of that module conditional so that you can do it manually for this particular API endpoint.

Code-wise for a resume operation, you're missing the [`start`](https://nodejs.org/docs/latest/api/fs.html#fs_fs_createwritestream_path_options) option that should be passed to `fs.createWriteStream()`. Additionally, you'll want to override `fs.createWriteStream()`'s default `flags` to be something like `'r+'` instead of `'w'`, to ensure that the file exists first.

**Comment by soubhikchatterjee** [comment]
Perfect @mscdex !

Thanks for the reply. For those who are struggling with the same issue, I was using Postman client to test the upload api endpoint. I am now using browser based axios client and/or node-fetch, and the file is now getting uploaded to the desired path.

One more question @mscdex 

When trying to upload large file (20+ gb), I am getting EPIPE error (sample error below). It works perfectly when I upload a 10gb file. I understand that EPIPE error occurs when node is executing a long running process (uploading and writing a 20 gb file to the disk in my case), how should i overcome this problem? 


```
FetchError: request to http://localhost:6969/upload failed, reason: write EPIPE
    at ClientRequest.<anonymous> (/Users/soubhikchatterjee/projects/backend/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:327:22)
    at Socket.socketErrorListener (_http_client.js:467:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EPIPE',
  code: 'EPIPE'
}

```

My client code is:

```
const fs = require("fs");
const path = require("path");

let url = "http://localhost:6969/upload";

let  filePath3 = "/Users/soubhikchatterjee/My Documents/BigFiles/20gb.img";

 
var stream3 = fs.createReadStream(filePath3, {
	highWaterMark: 2 * 1024 * 1024
	});
	stream3.on("data", function (chunk) {
	 console.log("stream3>", chunk.length);
});

const FormData = require("form-data");
const fetch = require("node-fetch");

 
function uploadImage(stream) {
  const form = new FormData();

	form.append("file[]", stream3, {
	  contentType: "multipart/form-data",
	  filename: path.basename(filePath3)
	});

  return fetch(url, {
    method: "POST",
    body: form
  })
    .then(res => res.json())
    .then(console.log)
    .catch(console.log);
}

uploadImage(stream);

```


I have tried this using browser side axios as well, after uploading the file for a while, it generates this error.

Please help 🙏🏻

`net::ERR_CONNECTION_RESET`

**Comment by lukepolo** [comment]
@soubhikchatterjee did you find a solution ?
