### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by vipulbhj** [mscdex/busboy#280]
Hey, @mscdex 

I am a noob programmer, who got curious and wanted to implement the `multipart/form-data` RFC. 

From what I understand till now, binary file data is just transmitted as is, but when I try to log multipart data I am getting in the `http.createServer`, it seems to be encoded in some way.

I was reading the source code of your implementation, and I say some conversion to "latin1", which I tried but didn't seem to work.

Is there something inherently wrong with my understanding or I am missing something super obvious ?

Thank for your time :)

*Data log of the image file and received data.*
![image](https://user-images.githubusercontent.com/33618798/151961066-ad562d06-4d90-4d16-806d-8ea42d3044ba.png)
![image](https://user-images.githubusercontent.com/33618798/151961067-6105b4e2-58dd-4b50-971a-f6cf25fa6b57.png)

**Comment by mscdex** [comment]
multipart/form-data itself does not encode the binary data in any way, it just defines the framing of each part with boundaries.

If you're referring to the occurrences of 0xEFBFBD in the second screenshot, that's the result of the binary data being treated as UTF-8. When converting binary data to UTF-8, any invalid bytes are replaced with `\uFFFD`. When that resulting string is then converted back to binary, those invalid bytes (`\uFFFD`) are turned into the byte sequence 0xEFBFBD.

The moral of the story is: don't convert your binary data to string, especially with a string encoding that is not binary safe (like UTF-8). latin1 is used in `busboy` because it *is* binary safe, which means if you wanted to convert it to UTF-8, you *could* do so safely (assuming the content is actually UTF-8).
