### ISSUE TITLE
Busybox handles requests like "streams" but requests still have to stored somewhere in the memory

### ISSUE THREAD

**Issue by SKFrozenCloud** [mscdex/busboy#304]
Busybox handles requests like "streams" where you have .on() and such but since the requests still have to be stored in the memory (when received) doesn't the files get stored in the memory as well until you move it from memory to a file on the disk?

My question is basically, doesn't the fact that requests still need to be stored in memory mean that memory leaks are possible even if you later store them on disk, if a lot of people uploaded lets say 8 GB files?

**Comment by mscdex** [comment]
The idea with node streams in general is that you have backpressure so that you're only buffering so much data in memory at any given time. So if you're piping a `busboy` file stream to disk and the disk can't keep up, the disk stream still hit its `highWaterMark` and tell the file stream to stop sending it data. When the file stream stops, its own buffer in memory will fill up and its upstream source (e.g. the http request stream) will stop sending data, and so on up the chain.

Obviously if you are not piping streams or not manually utilizing backpressure and instead simply buffering the entire file in memory first, then yes, you can run out of memory if you're allowing large files.

However this is not unique to `busboy` as it's how it is for any stream in node.

**Comment by SKFrozenCloud** [comment]
Ok, but let's say 10 people try to upload an 1GB file each with `multipart/form-data` requests.

This would mean that because the requests are `multipart/form-data` and 10 people uploaded 1GB at the same time, 10 GB of requests has to be stored somewhere at that instant for `busybox` to process it right? And if you only have 4 GB of server RAM it would run out of memory?

**Comment by mscdex** [comment]
> 10 GB of requests has to be stored, at the same time, somewhere at that instant for `busybox` to process it right?

No, that's the whole point of streams in node. You process chunks of data at a time. While there's nothing stopping you from buffering the entire file into memory, it's not really advisable for the reason you mentioned.

If you want to learn more about node streams, I'd refer you to the [relevant guide on nodejs.org](https://nodejs.org/en/docs/guides/backpressuring-in-streams/) and [the appropriate node.js streams documentation](https://nodejs.org/docs/latest/api/stream.html#types-of-streams). However the gist of it is that when you save/`pipe()` an incoming file to disk, it does so a chunk at a time until there is no more data left. This way you only store a minimal amount (with the limit being determined by the stream's `highWaterMark` value) of file data in memory at any given time.

**Comment by SKFrozenCloud** [comment]
Aha thanks, now I understand. I was confused since I thought the whole request had to be stored (on OS level) before the node server could process it (chunk by chunk).

**Comment by mscdex** [comment]
> I thought the whole request had to be stored (on OS level) before the node server could process it

No, it's chunks all the way from one end (client) to the other (server) and everywhere in between, including the OS/TCP stack. TCP itself also supports backpressure, which is why the whole streaming process from the socket/connection to your disk works as well as it does.
