### ISSUE TITLE
FEATURE REQUEST: Emit event when `limits.fileSize` or `limits.fieldSize` is reached

### ISSUE THREAD

**Issue by Mr-M1M3** [mscdex/busboy#307]
Currently, busboy doesn't emit any event when fileSize or fieldSize is reached, which will be very useful to work with!

**Comment by mscdex** [comment]
There is already an event emitted when `fileSize` is reached.

`fieldSize` does not have an event because there is no EventEmitter object for non-file fields, but you can instead check the `*Truncated` properties on the `info` object passed to `'field'` event handlers.

All of this is described in the readme.

**Comment by Mr-M1M3** [comment]
@mscdex I didn't read the whole description of `file` event. Sorry for that! I expected it to be in the list of the events that busby emits. I apologize for not being patient enough to read the whole description.
