### ISSUE TITLE
licenses in package.json is deprecated 

### ISSUE THREAD

**Issue by tobysmith568** [mscdex/busboy#337]
Hey

[The use of the `licenses` key in package.json files is deprecated](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#license:~:text=Those%20styles%20are%20now%20deprecated).

Would you please consider switching to an SPDX expression in the `license` key instead and then pushing out a patch release?

As of right now the npmjs.com website shows busboy as being unlicensed which means that no one can use it unless they double check the repo on GitHub for a license.

![image](https://user-images.githubusercontent.com/22356255/236627259-d50e641b-fcf7-4a04-b42f-86546e24f7f6.png)

Thanks :)

**Comment by mscdex** [comment]
I prefer keeping the direct URL to the license for now.

**Comment by lukeed** [comment]
Preference or not, it's deprecated & unsupported by any/all tools that are run audits to gather this metadata. It's not supported by `npm` itself, either.

Suggest keeping your `licenses` field w/ direct link, but add the [`"license"`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#license) field since that actually is what holds meaning. 

Currently, busboy and streamsearch are both flagged as "unlicensed" which also affects all their dependents.
