### ISSUE TITLE
Busboy not emitting finish event and after consuming the file not emitting end event

### ISSUE THREAD

**Issue by sherafghan** [mscdex/busboy#61]
This is pertaining to a negative use case which I have been trying to debug. I would expect busboy to throw an error somewhere. 

I am able to get Postman to send a document as part of a multipart POST request. 
Busboy is able to parse out the file, and pass off the file stream. This file stream does not emit the end event, causing my code to hang. And as a consequence busboy does not emit a 'finish' event either. 

Just wondering if this really is a bug, I haven't been able to find any informaiton on this anywhere.

Thanks.

**Comment by MarkTraceur** [comment]
I'm using busboy to handle a simple multipart form with one file and several fields, and I have the same problem. I tried looking for a different library, but apparently multipart form handling is the ghetto of node.js libraries right now.

My guess is it has to do with self._nparts in lib/types/multipart.js not getting decremented anywhere, but I'm having trouble following some of the code.

It's a damn shame this bug persisted in what I'm guessing is the most widely-used multipart handling library in the node.js universe. If there's a different library that you know of, I'd love suggestions, because this is pretty abysmal.

**Comment by mscdex** [comment]
@MarkTraceur Well it's hard to really do anything when I have no way to duplicate the problem on my side and I'm only given vague descriptions. If you can provide a minimal, reproducible example I would be more than happy to help.

**Comment by MarkTraceur** [comment]
Matter of fact,

https://github.com/MarkTraceur/busboy-buggy-bug

**Comment by mscdex** [comment]
@MarkTraceur With the code you're presented, there is no bug there. `file` events are passed *streams*. If you don't read from the stream, then backpressure will kick in eventually and the parser will stop parsing.

In your example, you are merely storing the stream object and not ever reading from it, so the parser stops. As an example, if you merely add a `file.resume()` inside the `file` event handler, you will see that the `field` event will be called after the file stream is drained. Due to the nature of `multipart/form-data`, there is no way to process multiple fields at once.

If the underlying/main issue is that you need the text input field *before* the file input field, then you have to literally submit the text field *before* the file input field because that is how the browser determines the order in which fields are sent in the request. Otherwise if you cannot ever delay the request stream, the only other option is to save files to disk/memory first. If you need that kind of functionality, you might look at using something that builds on top of busboy, like [`multer`](https://github.com/expressjs/multer) to reduce the amount of boilerplate.

**Comment by MarkTraceur** [comment]
OK, so the idea is that I have to use up the entire file stream before I can do anything with the 'finish' event? I was hoping to use streams and just pipe things together so I could avoid using the filesystem, but if I have to, I could use a buffer to store the data and pass it along to the next stream that way (which is essentially what multer did, until I butchered it to use pure streams).

Thanks for clarifying!

**Comment by mscdex** [comment]
@MarkTraceur You *can* pipe things together. So for example when you see a `file` event, you can pipe the file to S3 or GridFS or wherever you want. The important thing is that eventually the file stream will be read from so that the parser can continue doing its thing (without buffering the entire request into memory).

Just as a simple example, you could proxy files to another HTTP server like:

```javascript
busboy.on('file', function(fieldname, file) {
  var proxyReq = http.request({
    host: 'example.org',
    method: 'PUT',
    path: '/files/' + fieldname
  }, function(response) {
    // ...
    // drain response to prevent memory leaks unless you care about the response
    response.resume();
  });
  file.pipe(proxyReq);
});
```

**Comment by MarkTraceur** [comment]
Right, the trick is, I need the other fields for the rest of what I'm supposed to do with the image, so I'm stuck there.

**Comment by mscdex** [comment]
Ok in that case like I said, you need to place the text field(s) literally before the file field(s) before you submit the request. The reason is that is how the HTML/multipart/form-data spec defines the order in which fields are sent.

There are several solutions to this, including:

* Assuming it doesn't matter visually, just move the text field(s) before the file input field(s)
* If you cannot move the text field(s) (initially):
  * Move the text field(s) before the file input field(s) on form submit
  * Submit via AJAX instead using FormData and reorder when adding the fields to the FormData instance
  * Include hidden text field(s) with the correct `name` attribute before the file input field(s) and change the visible text field(s) to both not have a `name` attribute (so you don't duplicate values) and to update the hidden field when the text field value changes

**Comment by Raffiki** [comment]
@mscdex , can I ask about the proxy: I have a gist of a proxy server, which should stream a file upload towards another server: https://gist.github.com/Raffiki/2674a5646e7fb6dedadb

It seems I'm doing something wrong since the `on('file')` event on the endpoint server (line 12) is never called. 
Maybe I'm messing things up with my headers in the proxy?

**Comment by mscdex** [comment]
@Raffiki The proxy won't work as it it's currently coded because the proxy is not sending a `multipart/form-data`-formatted request, it's sending the raw file data, so the multipart boundary is never found.

If you want to proxy it as-is, you could just relay the original raw request data to the destination server (using the same `Content-Type` header at least).

**Comment by Raffiki** [comment]
mmm, it's sending the right headers, no? https://gist.github.com/Raffiki/2674a5646e7fb6dedadb#file-proxy-js-L12 There the boundary is set: `  'content-type': 'multipart/form-data; boundary=----WebKitFormBoundaryPRkZe5W4ngNmtmnq',` What else is needed for a properly formatted `multipart/form-data` request?

True, if the request is not to be touched, it can be piped to the destination with a oneliner. I'm just wondering how to break it open with busboy and push it along.

**Comment by mscdex** [comment]
`multipart/form-data` request bodies have one or more parts separated by the boundary given in the `Content-Type` header value, along with HTTP headers for each part. You can see what it looks like if you log the raw request data or view it in your browser's web development tools or with wireshark.
