### ISSUE TITLE
Empty formdata body stalls the parser

### ISSUE THREAD

**Issue by silverwind** [mscdex/busboy#95]
No full example yet, but the basic steps to reproduce would be this from a browser:

``` js
var xhr = new XMLHttpRequest();
var fd = new FormData();

fd.append('file', new Blob(), 'file.txt');
xhr.open('POST', '/');
xhr.send(fd);
```

The `file` event is raised correctly, but it seems to never emit a `finish`. I suspect the first empty file to be encountered will stall the whole upload request.

**Comment by fkei** [comment]
:+1:

**Comment by nicola** [comment]
samere here!

**Comment by BlaM** [comment]
The "[finish](https://github.com/yahoo/express-busboy/blob/master/index.js#L89)" handler is never called.

    <form action="/upload" method="post" enctype="multipart/form-data">
    <input name="file" type="file"> <button type="submit">Upload</button>
    </form>

**Comment by BlaM** [comment]
Okay, I have absolutely NO clue why that is, but adding this single line right before the line with [`file.on('end' ...`](https://github.com/mscdex/busboy/blob/master/lib/types/multipart.js#L194) fixes the issue:

        file.on('data', function() {});

**Comment by mscdex** [comment]
@BlaM An easier way is to just do `file.resume()` if you want to skip over the current file.

Adding that in this module would not be acceptable however since `busboy` cannot make any assumptions about what the consumer of this module is doing. Adding a `data` handler or calling `.resume()` will cause the stream to flow. If someone needs to perform an async operation before reading from the file, they would lose data. All ("streams2" or newer) streams since node v0.10 start in a paused state. FWIW a similar issue may arise if you only read part of the file stream, since `busboy` also handles backpressure properly.

**Comment by BlaM** [comment]
Understood :+1: 

I just issued a pull request to [yahoo/express-busboy](https://github.com/yahoo/express-busboy/issues/2), because their code was causing all my headaches.
