### ISSUE TITLE
Option to read fields first

### ISSUE THREAD

**Issue by hitchcott** [mscdex/busboy#97]
Sorry to re-open an old one -- but as mentioned in #43, there's an issue when you want to process the fields of a form before you handle the file stream. Basically if the file field appears first in the upload form, you can't read the fields until you `resume()` the stream.

Now let's say I want to have a form like so: 

```
        <input type="file" name='backupFile' accept=".tar"> Restore Backup
        <label>
        <input type="checkbox" value="drop" name="drop" checked='checked'>
          Drop Existing Data?
        </label>
```

AFAIK there's no way currently to know whether I need to drop data before I pipe it to the restore handler; I'd need to move the checkbox above the file.

I prose a `readFieldsFirst` option to get around this.

**Comment by mscdex** [comment]
This simply isn't possible (unless you save all files to disk first, which is not a goal of this module) because of the way `multipart/form-data` works and how browsers send forms.

What it boils down to is you have to place the non-file fields literally before the file fields *in the html*, as that is what determines the order in which the browser sends the form fields.

**Comment by mscdex** [comment]
There's several workarounds for this, such as using duplicate hidden elements, re-ordering the form right before submission, or using XHR2's FormData to create a separately ordered form.

An example of the first workaround would be (in your particular example) to have a hidden input element with `name="drop"` and drop the `name="drop"` from your actual checkbox. Then it's a matter of attaching an onchange handler for the checkbox so that it sets the value of the hidden input.

**Comment by hitchcott** [comment]
Thank you for the insights -- I now understand why it's not possible.

**Comment by jsdevtom** [comment]
@mscdex Thank you for explaining the limitations.

I noticed that `Dicer` uses `StreamSearch` here https://github.com/mscdex/dicer/blob/master/lib/Dicer.js#L124
Would it be possible/ make sense to search the stream for the delimiters, notes the positions of files, (whilst ignoring the `data` parameter from `StreamSearch` for files) and creating a "`fileStream`(s)" from the recorded position for the sake of memory efficiency?

**Comment by mscdex** [comment]
@jsdevtom That doesn't work because you have to do *something* with that data (imagine a multi-GB file upload that comes before non-file fields). Typically that would involve buffering in memory or writing to permanent storage somewhere. That's not the kind of decision `busboy` should be making.

It's easier/more efficient to just re-arrange the fields on the client side.

**Comment by jsdevtom** [comment]
@mscdex Got it thanks
